version: "3"

services:

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/app/nginx/conf.d
    # depends_on:
    #   - nuxt


  nuxt-app:
    container_name: nuxt-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'

