version: "3"

services:
  nuxt:
    build: ./app/
    container_name: nuxt
    restart: "no"
    ports:
      - "3000:3000"
    command:
      "npm run dev"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
