version: 2
jobs:
  deploy:
    docker:
      - image: 'circleci/php:7.3-stretch-node-browsers'
    steps:
      - type: shell
        shell: /bin/sh
        pwd: /
        command: sudo apt update && sudo apt install git -y && git --version

      - run: sudo apt update
      - run: sudo apt-get install rsync
      - add_ssh_keys
      - checkout
      - run:
          name: Setup env
          command: bash ./deploy_scripts/gendotenv.sh
      - run: yarn install
      - run: yarn generate
      - run: ssh-keyscan -H $PROD_SERVER >> ~/.ssh/known_hosts
      - run: >-
          rsync -avce ssh --delete ./dist/
          root@$PROD_SERVER:/var/www/evlx.app-js.pl/public_html
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
